[package]
name = "bevy-hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", default-features = false }

[features]
# Expose dynamic linking feature for bevy
dynamic_linking = ["bevy/dynamic_linking"]