[package]
name = "bevy-hello-world-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy-hello-world = { path = "../bevy-hello-world" }

[features]
dynamic_linking = ["bevy-hello-world/dynamic_linking"]